### ISSUE TITLE
how to prepare pickle data for train Pose Matching Module

### ISSUE THREAD

**Issue by wangarrb** [Guanghan/lighttrack#12]
To train Pose Matching Module, we need two pickle data, which are 

     data_path: ./unit_test/posetrack_train_data.pickle
     data_neg_path: ./unit_test/posetrack_train_data_negative.pickle
I think test_keypoints_to_graph.py can make the pickle, but it need to read json files from 'data/Data_2018/posetrack_data/gcn_openSVAI/train/*.json'. My question is, where these json files come from? Am I right? Look forward to your reply.

**Comment by Guanghan** [comment]
# Download training and validation data
cd graph/unit_test;
bash download_data.sh;
cd -;
