### ISSUE TITLE
 Ran out of input

### ISSUE THREAD

**Issue by zfyong** [Guanghan/lighttrack#13]
i met a below problem, when i train the pose match. it seems that there are something wrong with the file--"posetrack_train_data_negative.pickle".
```
 In [3]: with open("posetrack_train_data_negative.pickle", "rb") as f: 
   ...:     a = pickle.load(f) 
   ...:      
   ...:                                                                           
---------------------------------------------------------------------------
EOFError                                  Traceback (most recent call last)
<ipython-input-3-853959a245df> in <module>
      1 with open("posetrack_train_data_negative.pickle", "rb") as f:
----> 2     a = pickle.load(f)
      3 
      4 

EOFError: Ran out of input
```

**Comment by Guanghan** [comment]
Not sure whether this is the corruption of data. I will repeat the training on the server on Tuesday to make sure the training process is okay, and re-upload the data. Thanks!

**Comment by Guanghan** [comment]
@zfyong That was indeed the data problem. I re-uploaded the data, and it works on my machine. Please try again; it should be fine now.
