### ISSUE TITLE
download error 403

### ISSUE THREAD

**Issue by wwdguu** [Guanghan/lighttrack#18]
I meet 403 error when trying to download the pretrained model in your website. Is the link still valid?

**Comment by Guanghan** [comment]
@wwdguu  Sorry about the inconvenience. I have fixed the links. You should be able to download them now. (I tested downloading the files, but not exhaustively.)

**Comment by Bajrangi97** [comment]
I am also getting errors while downloading the pre-trained weight. Is there any alternate option?
