### ISSUE TITLE
How to run the camera inference in online mode?

### ISSUE THREAD

**Issue by WuZhuoran** [Guanghan/lighttrack#3]
Hi Guanghan,

Thanks for your work. Now in `demo_video_mobile.py`, we read an video and process with online mode (one by one frame.)

Do you have scripts with run the model with a camera? You will get one frame each time without knowing the total number of frames.

Thank you.

**Comment by Guanghan** [comment]
Hi Zhuoran,

Currently, I do not have such scripts available. Reason is... I did not have a local machine and a camera at hand. But this is an important feature, I plan to implement it in the near future. I believe it should be easy to adapt from the current code. Thanks!

**Comment by Guanghan** [comment]
@WuZhuoran 
The camera demo has been added. Please check the master. Thanks!
