### ISSUE TITLE
Where is evaluate.py for evaluation on PoseTrack 2018?

### ISSUE THREAD

**Issue by chaipangpang** [Guanghan/lighttrack#37]
Thanks for your great work.
I want to evaluation on PoseTrack 2018, but where is evaluate.py and "data/Data_2018/poseval/py "?

**Comment by chaipangpang** [comment]
Sorry, I find in [Evaluation Toolkit ](https://posetrack.net/users/download.php).

**Comment by Maqingyang** [comment]
@chaipangpang Do you know how to replace the path '--groundTruth=/export/LightTrack/data/Data_2018/gt_lighttrack/ \ ' in eval command?
