### ISSUE TITLE
Missing imports: logger, pprint, etc.

### ISSUE THREAD

**Issue by cclauss** [Guanghan/lighttrack#4]
[flake8](http://flake8.pycqa.org) testing of https://github.com/Guanghan/lighttrack on Python 3.7.1

$ __flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics__
```
./lib/tfflat/data_provider.py:359:21: F821 undefined name 'logger'
                    logger.exception("Cannot batch data. Perhaps they are of inconsistent shape?")
                    ^
./lib/tfflat/data_provider.py:361:29: F821 undefined name 'pprint'
                        s = pprint.pformat([x[k].shape for x in data_holder])
                            ^
./lib/tfflat/data_provider.py:362:25: F821 undefined name 'logger'
                        logger.error("Shape of all arrays to be batched: " + s)
                        ^
./HPE/dataset.py:17:19: F821 undefined name 'mask'
            rle = mask.frPyObjects([seg_ann], label.shape[0], label.shape[1])
                  ^
./HPE/dataset.py:21:13: F821 undefined name 'mask'
        m = mask.decode(rle) * 1
            ^
./HPE/dataset.py:231:23: F821 undefined name 'ori_img'
        seg = get_seg(ori_img.shape[0], ori_img.shape[1], d['segmentation'])
                      ^
./HPE/dataset.py:231:41: F821 undefined name 'ori_img'
        seg = get_seg(ori_img.shape[0], ori_img.shape[1], d['segmentation'])
                                        ^
./utils/standard_classes.py:23:20: F821 undefined name 'python_to_json'
        json_str = python_to_json(self.python_data)
                   ^
./utils/standard_classes.py:27:9: F821 undefined name 'write_json_to_file'
        write_json_to_file(self.python_data, output_json_path)
        ^
./utils/standard_classes.py:65:40: F821 undefined name 'pose_order'
        self.candidate["pose_order"] = pose_order
                                       ^
./utils/utils_convert_heatmap.py:138:44: E999 SyntaxError: invalid syntax
        print "[congrid] dimensions error. " \
                                           ^
./utils/utils_pose.py:197:44: E999 TabError: inconsistent use of tabs and spaces in indentation
	draw_heatmap(heatmap, joint_names[ith_map])
                                           ^
./utils/utils_io_file.py:95:16: F821 undefined name 'as_str'
        return as_str.index("1"), 63 - as_str.rindex("1")
               ^
./utils/utils_io_file.py:95:40: F821 undefined name 'as_str'
        return as_str.index("1"), 63 - as_str.rindex("1")
                                       ^
2     E999 SyntaxError: invalid syntax
12    F821 undefined name 'mask'
14
```
__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. These 5 are different from most other flake8 issues which are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

**Comment by wuxiaolianggit** [comment]
你有遇到过这个错误吗？请问大神是怎么解决的呢？

Traceback (most recent call last):
  File "demo_video_mobile.py", line 744, in <module>
    visualize_folder, output_video_path)
  File "demo_video_mobile.py", line 117, in light_track
    human_candidates = inference_yolov3(img_path)
  File "/wuxl/lighttrack/detector/detector_yolov3.py", line 66, in inference_yolov3
    detections = non_max_suppression(detections, opt.conf_thres, opt.nms_thres)[0].data.cpu().numpy()
  File "/wuxl/lighttrack/detector/detector_utils.py", line 274, in non_max_suppression
    image_pred = image_pred[(-score).argsort()]
AttributeError: 'Tensor' object has no attribute 'argsort'

**Comment by wuxiaolianggit** [comment]
@cclauss @Guanghan 你有遇到过这个错误吗？请问大神是怎么解决的呢？
Traceback (most recent call last):
File "demo_video_mobile.py", line 744, in 
visualize_folder, output_video_path)
File "demo_video_mobile.py", line 117, in light_track
human_candidates = inference_yolov3(img_path)
File "/wuxl/lighttrack/detector/detector_yolov3.py", line 66, in inference_yolov3
detections = non_max_suppression(detections, opt.conf_thres, opt.nms_thres)[0].data.cpu().numpy()
File "/wuxl/lighttrack/detector/detector_utils.py", line 274, in non_max_suppression
image_pred = image_pred[(-score).argsort()]
AttributeError: 'Tensor' object has no attribute 'argsort'

**Comment by Guanghan** [comment]
@wuxiaolianggit 
The issue has been answered in the other thread.

**Comment by Guanghan** [comment]
@cclauss Thanks for introducing lint tool flake. Will clean up issues on Monday.

**Comment by Guanghan** [comment]
@cclauss  Thanks again. The issues have been resolved.
