### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'argsort'

### ISSUE THREAD

**Issue by wuxiaolianggit** [Guanghan/lighttrack#5]
![image](https://user-images.githubusercontent.com/34123600/57576657-d8eff900-7497-11e9-8f15-866f410caefa.png)

how to slove the problem?

**Comment by Guanghan** [comment]
This is the same issue with this one:
https://github.com/ultralytics/yolov3/issues/136

I believe it is the wrong version of Pytorch. Are you using the same version with that provided in the virtual environment?

**Comment by Guanghan** [comment]
Confirmed on my Ubuntu machine. I installed Pytorch 0.4 at first for CUDA8 but it gives this error. Then I install CUDA9 and pytorch1.1, which solved the problem.
