### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './graph/GCN/epoch210_model.pt'

### ISSUE THREAD

**Issue by DunaiFuentes** [Guanghan/lighttrack#6]
Hello Guanghan,

First of all, thanks for this amazing repo. I followed the instructions to run the demo and run into this error:
FileNotFoundError: [Errno 2] No such file or directory: './graph/GCN/epoch210_model.pt'
The solution is as simple as changing './graph/GCN/epoch210_model.pt'  for './weights/GCN/epoch210_model.pt' in lighttrack/graph/config/inference.yaml

Hope it helps. Cheers,
Dunai

**Comment by Guanghan** [comment]
Hi Dunai, thank you so much for letting me know. I will update it accordingly:)
