### ISSUE TITLE
求教pip安装torchlight失败

### ISSUE THREAD

**Issue by 17702513221** [Guanghan/lighttrack#8]
pip install torchlight==1.0出现
  Could not find a version that satisfies the requirement torchlight==1.0 (from versions: 0.0.1)
No matching distribution found for torchlight==1.0
python demo_video_mobile.py出现
cannot import name 'str2bool'

**Comment by 17702513221** [comment]
我只能装0.0.1

**Comment by Guanghan** [comment]
@17702513221 你好！在readme的Getting Started里面有这样的命令，你操作一下即可～
cd lighttrack/lib;
make;

cd ../graph/torchlight;
python setup.py install

**Comment by 17702513221** [comment]
Installed /home/xs/anaconda3/envs/py36/lib/python3.6/site-packages/torchlight-1.0-py3.6.egg
Processing dependencies for torchlight==1.0
Finished processing dependencies for torchlight==1.0
(py36) xs@xs:~/lighttrack/graph/torchlight$ cd ../../
(py36) xs@xs:~/lighttrack$ python demo_video_mobile.py
Detector YOLOv3 options: Namespace(batch_size=1, checkpoint_model=None, conf_thres=0.8, config_path='detector/config/yolov3.cfg', img_size=416, n_cpu=8, nms_thres=0.4, weights_path='weights/YOLOv3/yolov3.weights')
PoseTrack order.
Traceback (most recent call last):
  File "demo_video_mobile.py", line 32, in <module>
    from graph import visualize_pose_matching
  File "/home/xs/lighttrack/graph/visualize_pose_matching.py", line 151, in <module>
    from gcn_utils.io import IO
  File "/home/xs/lighttrack/graph/gcn_utils/io.py", line 18, in <module>
    from torchlight import str2bool
ImportError: cannot import name 'str2bool'
我尝试过安装，还是不行

**Comment by Guanghan** [comment]
torchlight你可能用pip安装过，先uninstall，再用以下命令安装试试：
cd graph/torchlight;
python setup.py install
torchlight已经在graph里提供了代码，setup就是安装用的。

**Comment by 17702513221** [comment]
谢谢您，我成功运行了demo_video_mobile.py，我现在准备实验您的姿势匹配模块，是要先运行download_posetrack18.sh下载数据集对吗，可以向st-gcn一样识别特定动作吗

**Comment by ZBREE** [comment]
你好，我执行“python setup.py install”依然没解决问题，请问您后面是如何解决的
