### ISSUE TITLE
About demo_video_mobile.py running

### ISSUE THREAD

**Issue by ZHyuwind** [Guanghan/lighttrack#9]
Hello, I am interested in  your work, so I want to run demo_video_mobile.py.Flow your setps, I downloads all files, I meet a problem when I run demo_video_mobile.py. It is " No such file or directory: './graph/GCN/epoch210_model.pt'", I don't know how to deal with  it, please help me, I'll be very grateful with it. Another, I run in windows.Thanks!

**Comment by Guanghan** [comment]
@ZHyuwind The file actually is downloaded to "./weights/GCN/epoch210_model.pt". I had corrected the config file:
https://github.com/Guanghan/lighttrack/commit/6d308a0c1b30e05f0f31dd133d34f76877f491b4
You can update the path accordingly.
You should also use the latest demo file:
https://github.com/Guanghan/lighttrack/blob/master/demo_video_mobile.py

**Comment by ZHyuwind** [comment]
Thanks a lot! I will try.


 
---Original---
